Load remote stories from Tumblr API
DjangoGirls/djangogirls pull request #718
Opened 2021-12-21 15:31 UTC by ramonsaraiva

Closes #714 

Draft pull request to load remote stories from Tumblr API.

I added a django action to load the remote stories, as we don't have a backbone for having a periodic task that would try fetching new stories and load them from time to time (I think that's the desired approach, but an action seems like a good first step).

![image](https://user-images.githubusercontent.com/5559120/146955601-687244eb-1d00-45bf-af34-9a99822c616e.png)

The only caveat to the action is that you need to select 1 existing story to trigger it - it is possible to have actions without a queryset selected, but requires some code to change the action behavior that I felt it was a bit overkill, we can just select 1 story and trigger the action.

There's still one missing piece, for actual stories (`Your Django Story: ..` posts), that I need to load the first image in the NPF (https://www.tumblr.com/docs/npf) content. But I'll do that part once you guys agree with the approach.

2022-01-04 07:41 UTC, amakarudze commented
Thanks @ramonsaraiva for your work on this. 

While there is still the manual part involved in triggering the action, this is way better than actually having to enter the stories manually like we have to do now. So yes, we can use this approach for now. You can complete your work.

Sorry for late response on your PR, it was submitted during the holiday break when I had decided to unplug myself completely from the internet.

2022-01-05 18:48 UTC, ramonsaraiva commented
No worries @amakarudze - I unplugged myself as well 😃
I'll go ahead and wrap this up in the following days then, thanks for the feedback.

2022-01-11 08:37 UTC, amakarudze commented
> No worries @amakarudze - I unplugged myself as well 😃 I'll go ahead and wrap this up in the following days then, thanks for the feedback.

So I was trying to fix something on the server and then realised we can use commands `python manage.py ...` to do this like we do for fetching 'Your Django Story` using daily scheduled tasks on PythonAnywhere. Please see [these lines of code](https://github.com/DjangoGirls/djangogirls/blob/main/story/management/commands/fetch_stories.py#L1-L55). Sorry to provide this feedback a little too late.

2022-01-25 18:50 UTC, ramonsaraiva commented
That works as well 👍

2022-04-27 15:43 UTC, amakarudze commented
Hey @ramonsaraiva. Hope all is well with you. Do you have any idea on when you can move this from being a draft PR? Thanks for all your work on this.

2022-05-05 04:30 UTC, ramonsaraiva commented
Hey @amakarudze - I'll try getting back to this week/early next week. Been busy, sorry for leaving this stale. Should be an easy wrap, just gotta move the functionality to a command, I think the only missing piece content-wise for the posts was the image. I'll move it to review once I finalize that, thanks for poking.

2022-05-05 12:09 UTC, ramonsaraiva commented
Alrighty, I think that's how you imagined the management command to work. I'd love if you could fetch this branch locally and try it out yourself to make sure the stories are being loaded correctly.
```sh
python manage.py fetch_tumblr_stories
```
You can also run multiple times to make sure it won't re-fetch/re-create stories that already existing in our database.

If this looks good, I'll go ahead and write tests for this approach and then we can finally move to review :-)

2022-05-14 11:16 UTC, amakarudze commented
> Alrighty, I think that's how you imagined the management command to work. I'd love if you could fetch this branch locally and try it out yourself to make sure the stories are being loaded correctly.
> 
> ```shell
> python manage.py fetch_tumblr_stories
> ```
> 
> You can also run multiple times to make sure it won't re-fetch/re-create stories that already exist in our database.
> 
> If this looks good, I'll go ahead and write tests for this approach and then we can finally move to review :-)

Hello @ramonsaraiva, I checkout this PR locally and it only pulled out only 3 stories, which are the ones I didn't already have locally so you can add tests for it. I will check the code once the tests are there. Thanks for all your work on this! 🥳✨👏

2022-09-17 16:02 UTC, ramonsaraiva commented
@amakarudze @marksweb been ages, but finally got those tests written! Let me know if you have any suggestions or change requests. Cheers!

2022-09-17 19:36 UTC, marksweb commented
@ramonsaraiva excellent. I saw the notification for this earlier.

I'll try to review before Djangocon Europe this week 👍

2022-09-24 10:17 UTC, marksweb requested changes
Sorry this took a bit longer than I'd hoped. I've left a few comments. Nothing significant - just things to try to keep the code nice & tidy.

2022-09-24 10:17 UTC, marksweb commented on story/management/commands/fetch_tumblr_stories.py
> +    return (image_name, File(open(content[0], "rb")))
You could drop the outer braces from this & it'll still return a `tuple`.

```suggestion
    return image_name, File(open(content[0], "rb"))
```

2022-09-26 05:58 UTC, ramonsaraiva commented on story/services.py
> +        story = Story.objects.create(
I need to double check, but I'm pretty sure that if we bulk create stories, the `created` column will default to "now", unless we want to bulk create and then iterate through them to assign the proper "creation" time? We might save some writes but complexity tends to increase.

2022-09-26 11:21 UTC, marksweb commented on story/services.py
> +        story = Story.objects.create(
@ramonsaraiva Yes, you're right. `bulk_create` would only help if it didn't need the additional data setting after the objects are created. I'd written this before I'd really taken that into account.

2022-09-26 12:25 UTC, ramonsaraiva commented
@marksweb resolved the other requests, let me know if there's anything else you want me to change. Really appreciate the review.

2022-09-26 12:27 UTC, marksweb commented
@ramonsaraiva That looks perfect now. And thank you for type hinting it all as well - just this morning I've fixed a bug on something that could easily have been avoided if it had type hints (which I've added!)

@amakarudze I think this is good to release now 👍

2022-09-29 11:50 UTC, merged