TASK: README improvements
DjangoGirls/djangogirls pull request #742
Opened 2022-02-27 19:16 UTC by crydotsnake

2022-03-06 20:58 UTC, marksweb requested changes

2022-03-06 20:58 UTC, marksweb commented on README.md
> +```
I'd put this in 1 block as there's nothing between @crydotsnake 

```bash
pip install pip-tools
pip-sync
```

2022-03-06 20:58 UTC, marksweb commented on README.md
> +```
Again I'd do this as 1 block @crydotsnake 

```bash
pip-compile -U
pip-sync
```

2022-03-07 16:37 UTC, amakarudze reviewed
Thanks @crydotsnake for your work on this. If you can attend to the changes requested by @marksweb, I will be happy to merge this in.

2022-03-07 17:09 UTC, crydotsnake commented
Done! :) @amakarudze

2022-03-07 17:18 UTC, marksweb approved these changes

2022-03-07 17:51 UTC, amakarudze approved these changes

2022-03-07 17:55 UTC, amakarudze commented
> Done! :) @amakarudze

Thanks @crydotsnake 👍 . Merging this now!

2022-03-07 17:55 UTC, merged