ci: Add dependabot config to keep actions updated
DjangoGirls/djangogirls pull request #841
Opened 2023-01-17 08:19 UTC by marksweb

Using this config, dependabot will keep the versions within github actions (things like checkout, setup python etc) updated. It's set on a monthly basis which I find works well.

2023-01-17 12:12 UTC, ramonsaraiva commented
Wouldn't this stop the `pip` package ecosystem? Or that's enabled by default? I would believe that if we're "overwriting" or adding a custom dependabot configuration we'd need to set the pip package ecosystem as well. I guess even if it adds by default, we could be explicit about it and add that ecosystem with the interval that we want anyways. Wdyt?

2023-01-17 12:26 UTC, marksweb commented
@ramonsaraiva This is completely unrelated to `pip` and the project itself.

I've got this same file in django-sql-explorer. See here; https://github.com/groveco/django-sql-explorer/blob/master/.github/dependabot.yml

What it does is it gets the dependabot bot to raise PRs to upgrade action versions. See here;
https://github.com/groveco/django-sql-explorer/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+

2023-01-18 11:13 UTC, ramonsaraiva commented
Hmm, yeah I think I understand the part that this gets the dependabot to upgrade action versions.. But in the example you've shown in `django-sql-explorer`, I don't see dependabot PRs for the requirements files, but maybe that's intentional.

My only doubt is if whenever we add this `dependabot.yml` file, the bot will stop automatically creating PRs to upgrade the deps versions in our requirements file, because you're not adding the `pip` package ecosystem in it.

i.e.:
```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
```

2023-01-18 14:52 UTC, marksweb commented
@ramonsaraiva Yeah I don't get dependabot to do `pip` packages. That's better kept to the development workflow.

If there's a node pipeline, it's good to get dependabot to handle node as well.

2023-01-23 11:15 UTC, amakarudze requested changes
Thanks @marksweb but like @ramonsaraiva I kind of appreciate `pip` and `node js` dependabot workflows in keeping packages up-to-date so can we add them to this workflow?

2023-01-23 11:29 UTC, marksweb commented
@amakarudze Yeah sure 👍

2023-01-26 18:18 UTC, merged