Global partners
DjangoGirls/djangogirls pull request #851
Opened 2023-01-31 11:44 UTC by amakarudze

Changes in this PR
- Adds a `globalpartners` app for managing global partners and sending emails from the app
- Removes `Company` model from `jobboard/models.py`
- Alters field `company` of `Job` model to point to `GlobalPartner`

2023-02-01 01:54 UTC, marksweb approved these changes
This looks good.

My only feedback is just something I'd do differently - I'd store the sponsor level values as numbers rather than the strings. If any reporting were ever done on the data, numbers for how much people donate would be easier to query than the strings.

2023-02-02 02:15 UTC, amakarudze commented
Closes #836 

> This looks good.
> 
> My only feedback is just something I'd do differently - I'd store the sponsor level values as numbers rather than the strings. If any reporting were ever done on the data, numbers for how much people donate would be easier to query than the strings.

Thanks @marksweb. I have changed the sponsor levels to integers.

2023-02-02 10:32 UTC, marksweb commented
@amakarudze Sorry I should have given you an example rather than assume you'd know what I meant.

I'd make the choices;

```
[
    (100, "$100/month"),
    (250, "$250/month"),
    (500, "$500/month"),
    (1000, "$1,000/month"),
]
```

Then the database will store the integer, but where the user sees the choices they'll get the neat string to let them know the currency and the frequency of the payment.

I've added suggestions to the review to hopefully help out - you should just be able to accept each rather than actually making code changes.

I'd be good to also delete both migrations and generate the initial again so there's just 1.

2023-02-02 10:32 UTC, marksweb requested changes

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (100, 100),
```suggestion
    (100, "$100/month"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (250, 250),
```suggestion
    (250, "$250/month"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (500, 500),
```suggestion
    (500, "$500/month"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (1000, 1000),
```suggestion
    (1000, "$1,000/month"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (500, 500),
```suggestion
    (500, "Bronze ($500)"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (1000, 1000),
```suggestion
    (1000, "Silver ($1000)"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (2500, 2500),
```suggestion
    (2500, "Gold ($2,500)"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (5000, 5000),
```suggestion
    (5000, "Platinum ($5,000)"),
```

2023-02-02 10:32 UTC, marksweb commented on globalpartners/models.py
> +    (10000, 10000),
```suggestion
    (10000, "Diamond ($10,000)"),
```

2023-02-02 11:34 UTC, amakarudze commented
Is there a reason for pre-commit fa

> @amakarudze Sorry I should have given you an example rather than assume you'd know what I meant.
> 
> I'd make the choices;
> 
> ```
> [
>     (100, "$100/month"),
>     (250, "$250/month"),
>     (500, "$500/month"),
>     (1000, "$1,000/month"),
> ]
> ```
> 
> Then the database will store the integer, but where the user sees the choices they'll get the neat string to let them know the currency and the frequency of the payment.
> 
> I've added suggestions to the review to hopefully help out - you should just be able to accept each rather than actually making code changes.
> 
> I'd be good to also delete both migrations and generate the initial again so there's just 1.

Yeah I thought about that and thought it would be me using it anyway and just used numbers all the way.

2023-02-02 11:40 UTC, merged

2023-02-02 13:25 UTC, marksweb commented
@amakarudze The pre-commit failure appears to be a problem with isort

I think an update of the pre-commit hooks is in order. I'll raise a PR.