Add event funding information
DjangoGirls/djangogirls pull request #917
Opened 2023-10-28 11:14 UTC by amakarudze

Changes in this PR
- Add event funding template, view, url and tests

2023-10-31 15:44 UTC, marksweb requested changes

2023-10-31 15:44 UTC, marksweb commented on templates/organize/event_funding.html
> +    <h2>Apply for Sponsorship from our Global Partners</h2>
I suspect this should have `{% translate` tags in it so that we can provide it in the available languages?

2023-10-31 15:44 UTC, marksweb commented on tests/organize/test_views.py
> +    response = client.get(reverse("organize:event_funding"))
I think it'd be worth verifying the template used here as well.

```
def test_event_funding(client):
    response = client.get(reverse("organize:event_funding"))
    assert response.templates[0].name == "organize/event_funding.html"
    assert response.status_code == 200
```

2023-11-24 08:35 UTC, amakarudze commented
Thanks, @marksweb, I have been busy with DjangoCon Africa, so I can now look at this. 

Flake 8 is passing locally but failing for all new pull requests and what it's suggesting seems pretty weird to me. Should we consider changing this action @marksweb?

2023-11-24 09:42 UTC, marksweb commented
@amakarudze yeah I see. With the slack message in the management utils it might be complaining about the slack emojis.

I'd have to have a look from my laptop to be sure. But I can look at ignoring things that are actually valid or changing for the ruff linter which is what use these days.

2023-11-24 13:26 UTC, marksweb commented
Ok I got ruff in quicker than expected. #923

2023-12-31 02:57 UTC, merged