Fixes #920. Resolved MVDkeyError in Stripe token
DjangoGirls/djangogirls pull request #938
Opened 2024-01-26 10:04 UTC by Nandika-A

This error was raised due to a network connection problem (occurs rarely) between the stripe and the server, hence the token was not getting generated. Solutions are mentioned in [stripe's documentation](https://stripe.com/docs/error-handling?lang=python#connection-errors).
This is fixed by exception handling. Now it displays the following message instead of giving an error:
![Screenshot (56)](https://github.com/DjangoGirls/djangogirls/assets/93462818/c4cab132-e668-4538-a825-d556b815c4c3)

Idempotency keys are also added while creating a customer, to recover from connection error. UUID V4 is used to generate a string that could be used as Idempotency key, as mentioned in the documentation.

2024-01-29 10:34 UTC, amakarudze requested changes
Thanks for your work on this @Nandika-A, can you add tests for the lines you added so coverage passes?

2024-01-29 13:12 UTC, Nandika-A commented
> Thanks for your work on this @Nandika-A, can you add tests for the lines you added so coverage passes?

Ya sure!

2024-01-29 17:20 UTC, Nandika-A commented
Thanks for the review @amakarudze! I have added the tests. Could you please check it now?

2024-01-30 14:52 UTC, amakarudze approved these changes

2024-01-30 14:53 UTC, merged