Update email templates for global partners
DjangoGirls/djangogirls pull request #947
Opened 2024-02-09 09:41 UTC by amakarudze

Changes in this PR
- Update global partner email templates with the link to the new sponsor deck.
- Change the year to 2024 in sponsor email templates.
- Add slack invite link for new user  email.

2024-02-19 13:01 UTC, amakarudze commented
Hey @marksweb, could you take a look at this for me? Thanks

2024-02-20 00:30 UTC, marksweb commented on templates/emails/globalpartners/prospective_sponsor.html
> +<p>Please see attached our sponsors deck for 2024 https://drive.google.com/file/d/1fAmyAiEyLGiE0s6_z3PzgLByHNKzEVHB/view
@amakarudze Do these dates always want to be the current year?

To dynamically display the current year you should be able to use [`{% now "Y" %}`](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#now).

2024-02-22 21:59 UTC, marksweb requested changes

2024-02-24 17:03 UTC, amakarudze commented on globalpartners/management/commands/send_sponsor_thank_you_email.py
> +        if today == f"12/12/{year}":
Oh, thanks for that. I wasn't aware I pushed this already. Let me fix it and work on tests for it. This part wasn't supposed to be deployed now. Let me complete everything then. I had just planned to deploy the changes in the email templates lol.

 Thanks @marksweb!

2024-02-26 21:48 UTC, amakarudze commented on globalpartners/management/commands/send_sponsor_thank_you_email.py
> +        if today == f"12/12/{year}":
Have fixed all the management commands and added tests now @marksweb.

2024-02-27 00:54 UTC, marksweb approved these changes

2024-02-27 20:56 UTC, merged